<a href="https://colab.research.google.com/github/alwaysalearner1234/Statistics/blob/main/cosine_similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances


In [2]:
cosine_similarity([[3,1]],[[6,2]])


array([[1.]])

In [3]:
cosine_similarity([[3,0]],[[0,8]])


array([[0.]])

In [4]:
cosine_similarity([[3,1]],[[3,2]])


array([[0.96476382]])

In [5]:
cosine_similarity([[3,1]],[[3,2]])


array([[0.96476382]])

In [6]:
doc1 = """
iphone sales contributed to 70% of revenue. iphone demand is increasing by 20% yoy.
the main competitor phone galaxy recorded 5% less growth compared to iphone"
"""

doc2 = """
The upside pressure on volumes for the iPhone 12 series, historical outperformance
in the July-September time period heading into launch event, and further catalysts in relation
to outperformance for iPhone 13 volumes relative to lowered investor expectations implies a
very attractive set up for the shares.
"""

doc3 = """
samsung's flagship product galaxy is able to penetrate more into asian markets compared to
iphone. galaxy is redesigned with new look that appeals young demographics. 60% of samsung revenues
are coming from galaxy phone sales
"""

doc4 = """
Samsung Electronics unveils its Galaxy S21 flagship, with modest spec improvements
and a significantly lower price point. Galaxy S21 price is lower by ~20% (much like the iPhone 12A),
which highlights Samsung's focus on boosting shipments and regaining market share.
"""

In [7]:
import pandas as pd

df = pd.DataFrame([
        {'iPhone': 3,'galaxy': 1},
        {'iPhone': 2,'galaxy': 0},
        {'iPhone': 1,'galaxy': 3},
        {'iPhone': 1,'galaxy': 2},
    ],
    index=[
        "doc1",
        "doc2",
        "doc3",
        "doc4"
    ])

df

iPhone  galaxy
doc1       3       1
doc2       2       0
doc3       1       3
doc4       1       2

In [8]:
df.loc["doc1":"doc1"]


iPhone  galaxy
doc1       3       1

In [9]:
cosine_similarity(df.loc["doc1":"doc1"],df.loc["doc2":"doc2"])


array([[0.9486833]])

In [10]:
cosine_similarity(df.loc["doc1":"doc1"],df.loc["doc3":"doc3"])


array([[0.6]])

In [11]:
cosine_similarity(df.loc["doc3":"doc3"],df.loc["doc4":"doc4"])


array([[0.98994949]])

In [12]:
cosine_similarity(df.loc["doc1":"doc1"],df.loc["doc4":"doc4"])


array([[0.70710678]])

In [13]:
cosine_distances(df.loc["doc1":"doc1"],df.loc["doc4":"doc4"])


array([[0.29289322]])

In [14]:
1-0.70710678


0.29289321999999995

In [15]:
from sklearn.metrics.pairwise import cosine_similarity

# Directly pass the rows as 2D arrays using double brackets
cos_sim = cosine_similarity([df.loc["doc1"]], [df.loc["doc2"]])

print(cos_sim[0][0])  # Extract the scalar


0.9486832980505138


In [16]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Sample documents
docs = {
    "doc1": "I love programming in Python",
    "doc2": "Python programming is fun",
    "doc3": "I enjoy long walks in the park"
}

df = pd.DataFrame(list(docs.values()), index=docs.keys(), columns=["text"])


In [17]:
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df['text'])


In [18]:
cos_sim = cosine_similarity(tfidf_matrix)
cos_sim_df = pd.DataFrame(cos_sim, index=docs.keys(), columns=docs.keys())
print(cos_sim_df)


          doc1      doc2      doc3
doc1  1.000000  0.393677  0.148074
doc2  0.393677  1.000000  0.000000
doc3  0.148074  0.000000  1.000000


In [20]:
query = "I love coding in Python"


In [21]:
query_vec = vectorizer.transform([query])


In [22]:
query_vec = vectorizer.transform([query])


In [24]:
similarities = cosine_similarity(query_vec, tfidf_matrix)


In [25]:
import numpy as np

most_similar_idx = np.argmax(similarities)
most_similar_doc = df.index[most_similar_idx]
similarity_score = similarities[0][most_similar_idx]

print(f"Most similar document: {most_similar_doc} with similarity {similarity_score:.2f}")


Most similar document: doc1 with similarity 0.89
